### PR TITLE
Add `skip_timestamps` option

### LINKED ISSUE #318: .update() without changing timestamps
This is occasionally useful, it would be great to have a flag to disable callbacks and such.

### PR DESCRIPTION
**Pull request by stufro**
Resolves #318

This adds the ability to pass `skip_timestamps: true` to `update` and `update!` methods. To do this I had to change the `save` method to accept `skip_timestamps` so to avoid inconsistent behaviour I have also added the option to the `create` and `create!` methods.

To achieve this I had to remove the type definition of `args` on the method definition so that either a `Granite::ModelArgs` or a `NamedTuple` can be passed in with `skip_timestamps`, I originally added another method overload for this case as you can see in the first commit e6f917e4e383d69672a6acb6c5f39c299ef58d13. Open to thoughts on this.

I have also updated the crud.md docs to describe this feature and added a missing example for `save(validate: false)`

### CODE REVIEW

**Comment by robacarp** [comment]
Huh. I have wanted #update with skip_timestamps but never #create. Typically I want that because I want to "soft touch" some record without altering the breadcrumb trail for some reason...which I can't think of why I'd want to do that on a create. 

I think the timestamp columns are specified as NOT NULL (or at least they are in my databases). Wouldn't that cause a problem?

**Comment by stufro** [comment]
Hmm yeah you're right. I hadn't considered DB level constraints.

I've removed it from create and also squashed some of the commits to tidy up the branch.

**Comment by crimson-knight** [comment]
@stufro I think that you should keep the option to create records while skipping timestamps if the created_at and updated_at values are already present. That's the current gap, creating records in bulk that already have timestamps that want to be preserved but they aren't at the time of creation.

Database constraints will error on their own for the user, so I wouldn't worry about policing that from inside of Granite. I've had instances where we did imports and ignored the existence of the timestamps during creation but allowed them to be updated if/when the record was updated.

**Comment by stufro** [comment]
@crimson-knight ah yes I suppose that might also help with resolving #481?

I have made the change.

**Review by crimson-knight — APPROVED** [review]

**Pull request merged**
