### PR TITLE
Manually trigger callbacks

### PR DESCRIPTION
**Pull request by Blacksmoke16**
Depends on #194 As i used the Item class with the  `before_create` to base my tests off of.  Diff will just be two files once that gets merged in.

This PR wraps the callback run macros into functions that allow the users to call it to trigger a callback.  This is mainly intended to be a better solution to #185 as it allows for similar behavior without the extra caveats/issues.  

Example (from the UUID spec)
```Crystal
  class Item < Granite::ORM::Base
    adapter mysql
    table_name items

    primary item_id : String, auto: false
    field item_name : String

    before_create :generate_uuid

    def generate_uuid
      @item_id = UUID.random.to_s
    end
  end
```

```Crystal
items = [] of Item
items << Item.new(item_name: "item1")
items << Item.new(item_name: "item2")
items << Item.new(item_name: "item3")
items << Item.new(item_name: "item4")

items.all? { |item| item.item_id.nil? }.should be_true

items.each(&.run_before_create)

items.all? { |item| item.item_id.is_a?(String) }.should be_true

Item.import(items)
```
As in the above example this preserve the usefulness of having callbacks without integrating them into the `.import` function itself.

The only issue with this is if someone were to manually trigger their callbacks, then use `.save` for example, it would run that callback twice.  I don't really see this being an issue as there would be no reason to manually run them in that case.  

WDYT?

### CODE REVIEW

**Comment by Blacksmoke16** [comment]
I'm open to suggestions.  Would have to test if just `before_create` would interfere with the `before_create` macro tho?

**Comment by drujensen** [comment]
I think `run_before_create` is clear.

**Comment by Blacksmoke16** [comment]
@drujensen I just tested it with method names same as callback name and it seemed to work fine.  All tests passed.  I can change it to that if that would be preferable?

**Comment by drujensen** [comment]
@Blacksmoke16 thanks for your work on this.  excellent feature!  💯

**Pull request merged**
