### PR TITLE
fix Doesn't work in Crystal 1.4.0

### PR DESCRIPTION
**Pull request by VanyaNeytrino**
trying to solve the issue https://github.com/amberframework/granite/issues/463 if you know a better way, I will be glad to hear and make corrections.

### CODE REVIEW

**Comment by Blacksmoke16** [comment]
I'm pretty sure all you need to do is upgrade to Crystal `1.4.1`. This was a regression that was fixed in https://github.com/crystal-lang/crystal/pull/11995.

**Comment by VanyaNeytrino** [comment]
> I'm pretty sure all you need to do is upgrade to Crystal `1.4.1`. This was a regression that was fixed in [crystal-lang/crystal#11995](https://github.com/crystal-lang/crystal/pull/11995).
unfortunately this is not the case
Screenshot 2022-05-15 at 12 05 13

**Comment by Blacksmoke16** [comment]
Oh wow okay, I guess it's been broken since `1.0.0` then :grimacing:. In that case, I think a better fix would be replacing https://github.com/amberframework/granite/blob/master/src/granite/transactions.cr#L264 with a call to `set_timestamps`, much like it does in https://github.com/amberframework/granite/blob/master/src/granite/transactions.cr#L141 and that should fix it, and be backwards compatible.

**Comment by confact** [comment]
Tested master with 1.4.1 and #465 seemed to have fixed this issue.

**Comment by robacarp** [comment]
@VanyaNeytrino I think this is fixed elsewhere so I'm going to close. Feel free to re-open if there's other stuff in here that's relevant.

**Pull request closed without merging**
