### PR TITLE
Make migrator.create behave similarly to migrator.drop

### PR DESCRIPTION
**Pull request by coderobe**
Currently, migrator.drop will `DROP IF EXISTS` to avoid erroring when there's nothing to be dropped - similarly, create shouldn't error when there's nothing to create

### CODE REVIEW

**Comment by robacarp** [comment]
Hey @coderobe, thanks for your pull. The trick is, the table may exist but also be the wrong table. With the current code, it'll fail and produce an error when the table exists. By adding `IF NOT EXISTS` the action will still succeed, but the state is indeterminate. What do you think?

**Comment by coderobe** [comment]
Hmm, i think it's up to the developer to either migrate or drop outdated tables; Note that the behavior of drop_and_create doesn't change either. With this patch, you can make sure the database is initialized before using it without special dances. I don't think opening a db with a different schema and then trying to create existing tables is an action this should bother to support.

**Comment by robacarp** [comment]
looks like a legit test failure:

```text
  1) Granite::Migrator::Base #create_sql generates correct SQL with sqlite adapter
     Failure/Error: {% if env("CURRENT_ADAPTER") == "pg" %}
       Expected: "CREATE TABLE \"reviews\"(\n\"id\" INTEGER NOT NULL PRIMARY KEY,\n\"name\" VARCHAR(255)\n,\n\"downvotes\" INTEGER\n,\n\"upvotes\" INTEGER\n,\n\"sentiment\" FLOAT\n,\n\"interest\" REAL\n,\n\"published\" BOOL\n,\n\"created_at\" VARCHAR\n) ;\n"
            got: "CREATE TABLE IF NOT EXISTS \"reviews\"(\n\"id\" INTEGER NOT NULL PRIMARY KEY,\n\"name\" VARCHAR(255)\n,\n\"downvotes\" INTEGER\n,\n\"upvotes\" INTEGER\n,\n\"sentiment\" FLOAT\n,\n\"interest\" REAL\n,\n\"published\" BOOL\n,\n\"created_at\" VARCHAR\n) ;\n"
```

**Comment by coderobe** [comment]
oh well, that test needs to also be updated i suppose

**Comment by drujensen** [comment]
@coderobe Closing this.  Please reopen if you decide to fix the tests.

**Pull request closed without merging**
