### PR TITLE
Merge fork with enhancements/fixes

### PR DESCRIPTION
**Pull request by kalinon**
My fork has been getting a bit ahead so i wanted to open a PR with my working branch.

This includes the following bug fixes:

* fix allowing enum columns
* #455
* #454
* Fix issue where primary key can be pushed twice on create
* fix infinite recursion when searching with enum

It also includes the following enhancements:
* ameba recomendations
* add retry to adapter base
* add support for querying with Array(UUID)
* add `Relationship` annotation that is applied to methods which are defined relationships

### CODE REVIEW

**Comment by confact** [comment]
ping @Blacksmoke16 - Could this be merged? It solves some of my issues :)

**Comment by confact** [comment]
ping @drujensen - Could this be merged? It solves some of my issues :)

**Comment by confact** [comment]
@kalinon could you split this one up into smaller MR (one for each fix preferably) - So it is easier to review and maybe approve it?

**Comment by robacarp** [comment]
related: #462

**Comment by kalinon** [comment]
@confact i had already done that, but they were never merged. It soon grew and was hard to manage for me.

**Review by crimson-knight — APPROVED** [review]
Thank you for this!

**Pull request merged**
