### PR TITLE
Fix read_attribute, see #396

### LINKED ISSUE #396: Read_attribute does not work when column is array
```
In lib/granite/src/granite/columns.cr:146:58

 146 | def read_attribute(attribute_name : Symbol | String) : DB::Any
                                                              ^------
Error: method must return (Bool | Float32 | Float64 | Int32 | Int64 | Slice(UInt8) | String | Time | Nil) but it is returning (Array(Int32) | Array(Int64) | Bool | Int32 | Int64 | String | Time | Nil)
```

### PR DESCRIPTION
**Pull request by msa7**
Fixes #396

### CODE REVIEW

**Comment by Blacksmoke16** [comment]
Nice!  Maybe add a spec to ensure this doesn't regress?

**Comment by drujensen** [comment]
@msa7 will you be able to add a spec?  if not, maybe someone can pick up the mantel and get this over the finish line.

**Comment by msa7** [comment]
@drujensen I will do specs

**Comment by msa7** [comment]
I hope the spec is enough

**Pull request merged**
