### PR TITLE
Present includes base concern

### PR DESCRIPTION
**Pull request by OpakAlex**
I want to propose to create for Queries wrapper, where we can do basic query. This will allow us for next step with `includes?`, we can proxy pass into wrapper our associations and then send them to Result method. But i really want to understand if this is right idea.

### CODE REVIEW

**Comment by OpakAlex** [comment]
@drujensen i have one question, maybe my understanding of Crystal so pure, in this PR we have one spec which fails:
```
crystal spec spec/granite_spec.cr:16
```

```
class SomeClass
  def initialize(@model_class : Granite::Base.class); end

  def valid? : Bool
    @model_class.exists? 123
  end

  def table : String
    @model_class.table_name
  end
end

describe Granite::Base do
  it "class methods should work when type restricted to `Granite::Base`" do
    f = SomeClass.new(Teacher)
    f.valid?.should be_false
    f.table.should eq "teachers"
  end
end
```
It fails because of @model_class : Granite::Base.class, then i have same class into 
src/granite/querying.cr 
But inside proxy container: src/granite/querying_methods.cr. i have type `Teacher`.
I really can not understand why Crystal convert this type to base inside `src/granite/querying.cr`.
I am sorry if this is stupid question, but for now i have no ideas.

**Comment by OpakAlex** [comment]
@Blacksmoke16 @drujensen I have an issue, but first can you check my idea how to implement `eager_loading` at base, now it's just for 1 relation (NOT FINISHED), also here i need some help with crystal language(. I will wait for your ideas/feedbacks.
Error here is:
```
[0x105034e76] *Exception::CallStack::print_backtrace:Int32 +118
[0x1050030ee] __crystal_sigfault_handler +318
[0x7fff5cd07b5d] _sigtramp +29
[0x1052f24a2] *Granite::EagerLoading::ModelWrapper#model:NoReturn +2
[0x1052f24a6] *Granite::EagerLoading::ModelWrapper#model:NoReturn +6 (523888 times)
[0x1052f2496] *Granite::EagerLoading::ModelWrapper#book_id:NoReturn +6
[0x105219534] *Granite::EagerLoading::Container#resolve<BookReview.class, (String | Symbol), (String | Symbol | Nil), (Int32 | Nil)>:(Array(BookReview) | Array(Granite::EagerLoading::ModelWrapper)) +1236
[0x1052e6c21] *Granite::AssociationCollection(Book, BookReview)@Granite::AssociationCollection(Owner, Target)#all<String, Array(Bool | Float32 | Float64 | Int32 | Int64 | Slice(UInt8) | String | Time | Nil)>:(Array(BookReview) | Array(Granite::EagerLoading::ModelWrapper) | Granite::Collection(BookReview)) +113
[0x1052e6ba6] *Granite::AssociationCollection(Book, BookReview)@Granite::AssociationCollection(Owner, Target)#all:(Array(BookReview) | Array(Granite::EagerLoading::ModelWrapper) | Granite::Collection(BookReview)) +54
[0x1052e6af9] *Granite::AssociationCollection(Book, BookReview)@Granite::AssociationCollection(Owner, Target)#size:Int32 +9
[0x10501834a] ~procProc(Nil)@spec/granite/querying/query_builder_spec.cr:6 +650
[0x1051f84e6] *Spec::Example#internal_run<Time::Span, Proc(Nil)>:(Array(Spec::Result) | Nil) +246
[0x1051f83ca] *Spec::Example#run:Nil +1130
[0x1051f75b9] *Spec::ExampleGroup@Spec::Context#internal_run:Nil +137
[0x1051f7461] *Spec::ExampleGroup#run:Nil +433
[0x1051f75eb] *Spec::ExampleGroup@Spec::Context#internal_run:Nil +187
[0x1051f7461] *Spec::ExampleGroup#run:Nil +433
[0x1051f75eb] *Spec::ExampleGroup@Spec::Context#internal_run:Nil +187
[0x1051f7461] *Spec::ExampleGroup#run:Nil +433
[0x1051c62fb] *Spec::RootContext@Spec::Context#internal_run:Nil +187
[0x1051c6236] *Spec::RootContext#run:Nil +6
[0x10500b624] ~procProc(Int32, (Exception | Nil), Nil)@/usr/local/Cellar/crystal/0.35.0/src/spec/dsl.cr:266 +84
[0x1050fb4f2] *Crystal::AtExitHandlers::run<Int32, (Exception+ | Nil)>:Int32 +178
[0x10530ced5] *Crystal::main<Int32, Pointer(Pointer(UInt8))>:Int32 +117
[0x104ff6076] main +6

```

**Comment by drujensen** [comment]
@OpakAlex It looks like you are trying to accomplish the same thing as @c910335 did in his PR https://github.com/amberframework/granite/pull/375

Take a look at his and the comments from @Blacksmoke16

**Comment by OpakAlex** [comment]
> @OpakAlex It looks like you are trying to accomplish the same thing as @c910335 did in his PR #375
> 
> Take a look at his and the comments from @Blacksmoke16

Yes, thanks! Looking

**Comment by drujensen** [comment]
Closing in favor of #375 which just needs some work on caching.  @OpakAlex Maybe you can look at taking over that PR and adding an alternative caching solution.

**Pull request closed without merging**
