### PR TITLE
Support Crystal 0.34.0

### PR DESCRIPTION
**Pull request by drujensen**

### CODE REVIEW

**Comment by Blacksmoke16** [comment]
There's a bug in the current ameba version. Probably should save that one for later.

**Comment by drujensen** [comment]
@Blacksmoke16 So I should roll that back?

**Comment by Blacksmoke16** [comment]
If you can fix them then its fine.  But I think the macro ones will fail even tho they are valid.

**Comment by drujensen** [comment]
@Blacksmoke16 any ideas why Postgres 9.6 and 11 are failing?

**Comment by drujensen** [comment]
nm, forgot to update the crystal docker file to 0.34.0

**Comment by drujensen** [comment]
strange, pg 9.6 tests passed on my laptop when I updated the crystal version to 0.34.0

**Comment by drujensen** [comment]
looks like postgres docker image requires a password now.

**Comment by drujensen** [comment]
@Blacksmoke16 can you provide a quick review?

**Pull request merged**
