### PR TITLE
upgrade ameba to v1.3.1 which requires crystal v1.6

### PR DESCRIPTION
**Pull request by pan**

### CODE REVIEW

**Comment by pan** [comment]
Now everything is fixed.
```
$ bin/ameba 
Inspecting 104 files

........................................................................................................

Finished in 872.03 milliseconds
104 inspected, 0 failures
```

**Review by drujensen — APPROVED** [review]
Nice work.  so much cleaner and easier to read.  💯

**Review by robacarp — APPROVED** [review]
Nice work. Is it worthwhile to also add this to a github workflow?

**Comment by pan** [comment]
Yes after another [pull request](https://github.com/amberframework/granite/pull/470) is merged, `crystal spec` will also work.

**Pull request merged**
